<a href="https://colab.research.google.com/github/CyanideBoy/RDE-in-NLP/blob/master/MNIST_RDE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!python train.py

Running on cuda:0
Building model..
Model Built.
Initializing optimizer..
Optimizer initialized.
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch.Size([128, 1, 28, 28])
torch

In [49]:
!python RelMapGeneration.py

Running on cuda:0
Building model..
Model Built.
tensor([[-20.9473, -26.4182, -28.9185, -22.8765, -26.2741, -22.9106, -40.8576,
           0.0000, -26.1675, -13.8078]])
0.04820273444056511
0.04380592703819275
0.039542824029922485
0.03519726172089577
0.030229777097702026
0.026543492451310158
0.023511942476034164
0.021107368171215057
0.019020823761820793
0.017231527715921402
0.015788856893777847
0.015037494711577892
0.01366832759231329
0.013096114620566368
0.012655540369451046
0.011987786740064621
0.01137518510222435
0.011599638499319553
0.01089872233569622
0.01018276996910572
0.014442977495491505
0.009584669023752213
0.009595195762813091
0.009249059483408928
0.009102443233132362
0.008783768862485886
0.00878858007490635
0.009453210048377514
0.008416839875280857
0.008120942860841751
0.008058389648795128
tensor([[-36.4964, -36.7899, -38.5746, -19.1764, -34.8610,   0.0000, -29.2038,
         -38.3050, -25.9984, -18.8817]])
0.05126865953207016
0.04943305253982544
0.0482393279671669
0.04681204

In [51]:
!python AnalyzeRelMaps.py

tensor([7.9930e-10, 3.3631e-12, 2.7598e-13, 1.1611e-10, 3.8842e-12, 1.1221e-10,
        1.8020e-18, 1.0000e+00, 4.3213e-12, 1.0078e-06])
tensor([1.4119e-16, 1.0528e-16, 1.7670e-17, 4.6968e-09, 7.2456e-16, 1.0000e+00,
        2.0748e-13, 2.3140e-17, 5.1174e-12, 6.3063e-09])
tensor([3.6076e-17, 1.1252e-12, 1.0281e-11, 1.0000e+00, 6.3814e-17, 1.2824e-08,
        7.6472e-15, 2.5942e-14, 7.1779e-13, 4.2636e-12])
tensor([7.3003e-16, 1.0416e-17, 1.5636e-17, 1.2392e-11, 4.5798e-16, 9.9999e-01,
        7.5329e-12, 7.5354e-19, 7.6695e-06, 1.4966e-09])
tensor([2.7422e-11, 1.6982e-09, 1.4572e-09, 4.6012e-14, 1.0000e+00, 2.3284e-10,
        4.3312e-09, 1.3223e-10, 7.1872e-13, 9.6050e-10])
tensor([5.5634e-07, 3.4742e-07, 1.7428e-08, 2.3621e-03, 3.4756e-04, 4.1768e-01,
        8.1383e-08, 2.5054e-05, 6.8733e-06, 5.7958e-01])
tensor([1.0000e+00, 5.4364e-13, 5.8164e-11, 3.7957e-15, 1.2502e-14, 1.4842e-13,
        6.7006e-09, 1.9114e-13, 1.1888e-11, 9.8180e-11])
tensor([1.0000e+00, 1.1490e-10, 2.3686e-1

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!mv New drive/My\ Drive/